version: '3'

services:
###> doctrine/doctrine-bundle ###
    database:
      container_name: database
      image: "mariadb:10.5"
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: portfolio
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
      platform: linux/amd64
      ports:
        - '4306:3306'
      volumes:
        - ./.docker/mysql:/var/lib/mysql
    php:
      container_name: php
      build:
        context: .docker/php
      platform: linux/amd64
      ports:
        - '9000:9000'
      volumes:
        - ./app:/var/www/portfolio
      depends_on:
        - database
    nginx:
      container_name: nginx
      build:
        context: .docker/nginx
      platform: linux/amd64
      ports:
        - '8080:80'
      volumes:
        - ./app:/var/www/portfolio
        - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - database
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
