framework:
    default_locale: ru
    translator:
        paths:
            - '%kernel.project_dir%/src/User/Infrastructure/translations'
            - '%kernel.project_dir%/src/Security/Infrastructure/translations'
            - '%kernel.project_dir%/translations'
        fallbacks:
            - en
            - ru
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
